let num1=10;
let num2=5;
let suma = num1 + num2;
let resta = num1 - num2;
let multiplicacion = num1 * num2;
let division = num1 / num2;
document.writeln("el primer numero es: " + num1 + "<br>");
document.writeln("el segundo numero es: " + num2 + "<br>");
document.writeln("el resultado de la suma es: " + suma + "<br>");
document.writeln("el resultado de la resta es: " + resta + "<br>");
document.writeln("el resultado de la multiplicacion es: " + multiplicacion + "<br>");
document.writeln("el resultado de la division es: " + division + "<br>");
